FROM node:14.15.4-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

# install dependencies
COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install --frozen-lockfile --prod --network-timeout 600000

# add app
COPY . .
RUN yarn build


# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html/ui
# new
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]