version: "3.7"

services:
  gateway:
    build:
      context: ./gateway
    environment:
      TRAEFIK_HOST: "traefik.roqqett.localtest.me"
      BACKEND_URL: http://backend
      FRONTEND_URL: http://frontend
      API_HOST: ${API_HOST}
    ports:
      - "5010:80"
    volumes:
      - "./gateway/configs:/configs"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
    ports:
      - 7654:80

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   environment:
  #     REACT_APP_API_URL: ${REACT_APP_API_URL}
  #   ports:
  #     - 7655:80

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod.yml
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    ports:
      - 7655:80

  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: big-daddy-ballers
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27020:27017
    volumes:
      - ./database/out:/data/db
