version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
    ports:
      - 7654:80
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: big-daddy-ballers
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27020:27017
    volumes:
      - ./database/out:/data/db
