log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.0/8" # Loopback addresses to localhost
        - "10.0.0.0/8" # Local communications within private network
        - "172.16.0.0/12" # Local communications within private network
        - "192.168.0.0/16" # Local communications within private network

providers:
  file:
    directory: /configs
